name: RankPlugin
version: '${version}'
main: org.rankplugin.rankplugin.RankPlugin
api-version: '1.16'
commands:
  rank:
    description: "Показать текущий ранг"
    usage: "/rank"
  rankscore:
    description: "Вернуть только число очков"
    usage: "/rankscore"
  ranksystem:
    description: "Управление RankPlugin"
    usage: "/ranksystem reload"
    permission: "rankplugin.admin"
  reset:
    description: "Сброс рангового счёта игрока"
    usage: "/reset <ник>"
    permission: "rankplugin.admin"
depend: [PlaceholderAPI]